### ISSUE TITLE
Crash with big pdf file

### ISSUE THREAD

**Issue by abbasiehsan1991** [googlesamples/android-PdfRendererBasic#12]
Hello
When i use this code with pdf file has less than 10 pages it works correctly, but when i want to show an pdf file with more than 10 pages my app will crash with this errors 
![capture](https://cloud.githubusercontent.com/assets/23223511/20462361/0fe491a2-af31-11e6-96a0-482d24b132fd.PNG)

I can't find it out , Please help me.
Thank you.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
