### ISSUE TITLE
How to open pdf file from the sd Instance of Assets folder.

### ISSUE THREAD

**Issue by Gowthaman-Uohamctechnologies** [googlesamples/android-PdfRendererBasic#16]
I have file path some like this  (File pdfFile = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/Bosch/" + "/All_files/"+"Week"+position+".pptx");// Instance of get file from assets folder i am fetching file from sd card.how to achieve this..please help me sir.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
