### ISSUE TITLE
can not read custom fonts

### ISSUE THREAD

**Issue by bauer-bao** [googlesamples/android-PdfRendererBasic#18]
Hi this is a link which client want to read. PdfRenderer cannot read it.

https://igenbucket.s3.ap-south-1.amazonaws.com/1505737193910_1505737193728History-hin-1A.pdf

**Comment by vitalnik** [comment]
Text with custom/embedded fonts appears as blank space using PDFRenderer on Android API 23,24,25. On Android 26 text is displayed, but fonts are not displayed correctly. Works only on API 21. Looks like a bug in PDFRenderer.

**Comment by AswinpAshok** [comment]
Any updates on this? I am having the same issue.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
