### ISSUE TITLE
black border around content

### ISSUE THREAD

**Issue by 2ndGAB** [googlesamples/android-PdfRendererBasic#19]
Hello,
 I'm trying to use PDFRenderer to convert a PDF file generated by the Android' PrintManager
Below is this generated pdf file which seems perfectly correct.
[TestPrint.pdf](https://github.com/googlesamples/android-PdfRendererBasic/files/1638910/TestPrint.pdf)
And here is the code I use to convert this file in a bitmap.

        mCurrentPage = mPdfRenderer.openPage(index);

        int width = (int)(203.0 / 72.0 * mCurrentPage.getWidth() + 0.5);
        int height = (int)(203.0 / 72.0 * mCurrentPage.getHeight() + 0.5);

        Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);

        mCurrentPage.render(bitmap, null, null, PdfRenderer.Page.RENDER_MODE_FOR_PRINT);

And below is the generated Bitmap. could you please tell me where does this 80 pixels wide black border comes from?
![screenshot_19700129-125550](https://user-images.githubusercontent.com/14370028/35042796-e0eeeec6-fb81-11e7-923a-55cb9188d9e4.png)

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
