### ISSUE TITLE
[ZIP3] No create document. Error:

### ISSUE THREAD

**Issue by ZIP3** [googlesamples/android-PdfRendererBasic#2]
Hi~
I'm making test app using your code but following system err was happened.
(sample.pdf was added to assets folder)
Please help me~

[Logcat]
09-03 17:43:03.538 D 13260    13260    ZIP3                                                          : {ParcelFileDescriptor: FileDescriptor[35]} 
09-03 17:43:03.548 W 13260    13260    System.err:                                                java.io.IOException: not create document. Error: 
09-03 17:43:03.548 W 13260    13260    System.err:                                                  at android.graphics.pdf.PdfRenderer.nativeCreate(Native Method) 
09-03 17:43:03.548 W 13260    13260    System.err:                                                  at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:153) 
09-03 17:43:03.548 W 13260    13260    System.err:                                                  at com.example.zip3testapp.MainActivity.openRenderer(MainActivity.java:178) 
09-03 17:43:03.548 W 13260    13260    System.err:                                                  at com.example.zip3testapp.MainActivity.onResume(MainActivity.java:267) 

[Source]
        mFileDescriptor = assetManager.openFd("sample.pdf").getParcelFileDescriptor();
        Log.d("ZIP3", mFileDescriptor.toString());
        PdfRenderer mPdfRenderer = new PdfRenderer(mFileDescriptor);

P.S.
1. I tested this with GS6(platform ver.5.1.1).
2. I moved file to sdcard and checked this again but there's a same error.

**Comment by ZIP3** [comment]
I found the reason.
"sample.pdf" in the uploaded code was broken. I replaced it and it works now.

**Comment by adambdev** [comment]
I have replace the sample pdf with my file still getting same error.

**Comment by chetnabishnoi** [comment]
Even I am getting the same error. Is anybody able to resolve it?

**Comment by gunjot-mansa** [comment]
Any solution yet??

**Comment by rajeevjaiswal** [comment]
same issue

**Comment by ibrerode** [comment]
same issue.

**Comment by wangchauyan** [comment]
Guys, I think you should keep the old version gradle, dont upgrade to 2.2.0

**Comment by cluelin** [comment]
I did
1. Change pdf file
2. Change pdf file location to res/raw and used 
Resources res = context.getResources(); 
mFileDescriptor = res.openRawResourceFd(R.raw.sample).getParcelFileDescriptor();

this code instead
3. downgrade gradle version to 2.14

above options doesn't work for me. 

only work is 
pdf file in asset copy to application file directory. and read it. 

but I think it's slow. so I keep search something work. 

Thanks.

**Comment by KrawczykPawel** [comment]
I had the same problem. I read the file from the sdcard and it works.

**Comment by ghost** [comment]
the old version gradle 2.14 is ok

**Comment by Gowthaman-Uohamctechnologies** [comment]
@KrawczykPawel hi sir,please help me, how i can read file from the sdcard.i tried but not working

**Comment by yaraki** [comment]
This is how you can read a file from the app cache directory. Reading from the SD card can be done in the same manner, just a different path.
https://github.com/googlesamples/android-PdfRendererBasic/blob/master/Application/src/main/java/com/example/android/pdfrendererbasic/PdfRendererBasicFragment.java#L166

**Comment by Gowthaman-Uohamctechnologies** [comment]
@yaraki Thank you sir i did,how to make pinch zoom please help.
