### ISSUE TITLE
Show Pdf in Recyclerview

### ISSUE THREAD

**Issue by AhmadullahSaikat** [googlesamples/android-PdfRendererBasic#24]
Did anyone implement this code for recyclerview.

**Comment by aayushthakur** [comment]
I have implemented this.

**Comment by AhmadullahSaikat** [comment]
Can you please send me the source code.
my email address is:  saikatuoda@gmail.com

**Comment by hunter-t** [comment]
@aayushthakur That would be very appreciated if you could share your solution with people.

**Comment by LaatonWalaBhoot** [comment]
This is my implementation of loading PDF in Recycler View with pinch zooming. Only API 21+. Will be looking for anyone to contribute to make a legacy version and improve it further...
https://github.com/LaatonWalaBhoot/PdfRedererRecyclerView

**Comment by srgiitd** [comment]
The sample given by @LaatonWalaBhoot is in Kotlin. Has anybody done it with java? Please share. Thanks.

**Comment by LaatonWalaBhoot** [comment]
I can do this in Java as well... @srgiitd

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
