### ISSUE TITLE
The PDF content can't be zoomed in or out

### ISSUE THREAD

**Issue by peter-zhijia-zheng** [googlesamples/android-PdfRendererBasic#3]
I've implemented it, and want to contribute my change, may I?

**Comment by mainr** [comment]
Of course you may.

The normal way to contribute changes is to:
1. Clone the repository to a local copy.
2. Make your changes & commit them to your local copy.
3. Issue a 'pull request'.
Google will verify you have signed a CLA ("Contributor License Agreement" -  see the thread on the current pull request against this project).
Your pull request will document exactly what changes you made and to which files. The changes can then be reviewed, and (EVENTUALLY, though it seems google is VERY SLOW at this...) be merged into the repository.

**Comment by mainr** [comment]
Actually, since I'll be implementing zooming myself, I'm interested in your patch.

**Comment by jaredsburrows** [comment]
Can you post your solution here?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
