### ISSUE TITLE
Upstream issue with PdfRenderer

### ISSUE THREAD

**Issue by rrshaban** [googlesamples/android-PdfRendererBasic#7]
"This is an odd one; it's probably a variation on Issue #82838, in which when attempting to use PdfRenderer to display Assets, the wrong Asset is used.

What seems to be the problem is that behavior of PdfRenderer to display Assets depends upon the _order_ of entries within the .apk. If the META-INF entries are _first_ in the .apk, then PdfRenderer won't display PDF assets at all."

https://code.google.com/p/android/issues/detail?id=82841

**Comment by benedictusc** [comment]
Facing this issue too, anyone know a fix?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
