### ISSUE TITLE
How to zoom page ??

### ISSUE THREAD

**Issue by CHRehan** [googlesamples/android-PdfRendererBasic#9]
i want to know how to enable zoom page rather to double click or tap ??

**Comment by wangchauyan** [comment]
basically, you should implement this yourself, cause PdfRender translates the pdf page into bitmap, so, if you wanna use pinch zoom, simplest way is to implement gesture for image view.

**Comment by cluelin** [comment]
use this library 

https://github.com/chrisbanes/PhotoView

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
